version = 1

# A simple glob of all files in resources/img/
[[annotations]]
path = [
     ".github/workflows/build.yml",
     "Cargo.toml",
     "Cargo.lock",
     "REUSE.toml",
     "spread.yaml",
     "spread-lxd.yaml",
]
SPDX-FileCopyrightText = "2024 Maciej Borzecki <maciek.borzecki@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
     "README.md",
     ".gitignore",
]
SPDX-FileCopyrightText = "2024 Maciej Borzecki <maciek.borzecki@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"
